services:
    db:
        image: postgres:16-alpine
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 3s
            timeout: 3s
            retries: 10
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        networks:
            - agentic_network
        ports:
            - 5432:5432
        volumes:
            - ~/langfuse_database_data_fc_v2:/var/lib/postgresql/data
